/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.*;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.logging.*;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tugasakhir.Database;
import tugasakhir.daftarAkun;
import mulaiRunDriverDisini.driver;
import tugasakhir.member;
import tugasakhir.profile;

/**
 *
 * @author ASUS
 */
public class Dashboard_admin extends javax.swing.JFrame {
    DefaultTableModel tbMember;
    DefaultTableModel tbPeminjam;
    DefaultTableModel tbBuku;
    
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    public String url = "jdbc:mysql://localhost/tugasakhir";
    public String user = "root";
    public String pass = "";
    Database db;
    ArrayList<member> Member = new ArrayList();
    DefaultListModel<String> listMember = new DefaultListModel<>();
    
    public Dashboard_admin() {
        setTitle("Perpus.id");
        initComponents();
        db = new Database();
        
        String []judulTbMember = {"Library Id", "Nama Member", "Nomor Hp", "Email", "Tanggal Lahir"};
        tbMember = new DefaultTableModel(judulTbMember, 0);
        jTable1.setModel(tbMember);
        tampilMember();
        
        String []judulTbPeminjam = {"Library Id", "Nama Peminjam", "Id Buku", "Nama Buku", "Tanggal Pinjam"};
        tbPeminjam = new DefaultTableModel(judulTbPeminjam, 0);
        jTable2.setModel(tbPeminjam);
        tampilPeminjam();
        
        String []judulTbBuku = {"Id Buku", "Judul Buku", "Penerbit", "Stok"};
        tbBuku = new DefaultTableModel(judulTbBuku, 0);
        jTable3.setModel(tbBuku);
        tampilBuku();
        
        btnClearSearch.setEnabled(false);
    }
    
        public void tampilMember(){
            try {
                Connection konek = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugasakhir","root","");
                ResultSet rs = konek.createStatement().executeQuery("SELECT * FROM member");
                while (rs.next()) {
                    String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)};
                    tbMember.addRow(data);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Dashboard_admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        public void tampilPeminjam() {
            try {
                Connection konek = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugasakhir","root","");
                ResultSet rs = konek.createStatement().executeQuery("SELECT * FROM peminjaman");
                while (rs.next()) {
                        String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)};
                        tbPeminjam.addRow(data);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Dashboard_admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        public void tampilBuku() {
        try {
            Connection konek = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugasakhir","root","");
            ResultSet rs = konek.createStatement().executeQuery("SELECT * FROM buku");
            while (rs.next()) {
                        String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)};
                        tbBuku.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profile = new javax.swing.JLabel();
        namaProfile = new javax.swing.JLabel();
        hello = new javax.swing.JLabel();
        memberList = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnPeminjaman = new javax.swing.JLabel();
        btnDataBuku = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelTbMember = new javax.swing.JLabel();
        btnCariMember = new javax.swing.JButton();
        inputCariMember = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnCariTbPeminjam = new javax.swing.JButton();
        inputCariPeminjam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnCariTbBuku = new javax.swing.JButton();
        inputCariBuku = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnClearSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        namaProfile.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        namaProfile.setForeground(new java.awt.Color(255, 255, 255));
        namaProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/iconProfile.png"))); // NOI18N
        namaProfile.setText("--");
        namaProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaProfileMouseClicked(evt);
            }
        });
        getContentPane().add(namaProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 50));

        hello.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hello.setForeground(new java.awt.Color(255, 255, 255));
        hello.setText("--");
        hello.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                helloAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(hello, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 320, 60));

        memberList.setBackground(new java.awt.Color(255, 255, 255));
        memberList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        memberList.setForeground(new java.awt.Color(255, 255, 255));
        memberList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/user-list.png"))); // NOI18N
        memberList.setText("     Member List");
        memberList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memberListMouseClicked(evt);
            }
        });
        getContentPane().add(memberList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 50));

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 120, -1));

        btnPeminjaman.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        btnPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/iconKertas.png"))); // NOI18N
        btnPeminjaman.setText("Peminjaman Buku");
        btnPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPeminjamanMouseClicked(evt);
            }
        });
        getContentPane().add(btnPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 190, 50));

        btnDataBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDataBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnDataBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/iconBuku.png"))); // NOI18N
        btnDataBuku.setText("Data Buku");
        btnDataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDataBukuMouseClicked(evt);
            }
        });
        getContentPane().add(btnDataBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 670, 100));

        labelTbMember.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTbMember.setText("Data Member");
        getContentPane().add(labelTbMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        btnCariMember.setText("Cari");
        btnCariMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariMemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnCariMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, -1, -1));

        inputCariMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCariMemberActionPerformed(evt);
            }
        });
        getContentPane().add(inputCariMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 160, -1));

        jLabel5.setText("Cari berdasarkan nama buku");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Data Peminjam");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 670, 100));

        btnCariTbPeminjam.setText("Cari");
        btnCariTbPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariTbPeminjamActionPerformed(evt);
            }
        });
        getContentPane().add(btnCariTbPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, -1, -1));
        getContentPane().add(inputCariPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 150, -1));

        jLabel7.setText("Cari berdasarkan nama member");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 200, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Data Buku");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 670, 100));

        btnCariTbBuku.setText("Cari");
        btnCariTbBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariTbBukuActionPerformed(evt);
            }
        });
        getContentPane().add(btnCariTbBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, -1, -1));
        getContentPane().add(inputCariBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 150, -1));

        jLabel9.setText("Cari berdasarkan nama peminjam");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 200, -1));

        btnClearSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnClearSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClearSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnClearSearch.setText("Clear");
        btnClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnClearSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/4 Dashboard.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:

        db.connect();
        try{
            conn = DriverManager.getConnection(url,user,pass);
            stmt = conn.createStatement();
            String login = ("DELETE FROM logIn_admin");
            stmt.executeUpdate(login);

        }catch(SQLException e){
            Logger.getLogger(driver.class.getName()).log(Level.SEVERE, null, e);
        }
        db.disconnect();
        JOptionPane.showMessageDialog(rootPane,"Anda telah Logout","Success",1);
        System.exit(0);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
        profile p = new profile();
        if(evt.getClickCount() == 1){
            p.getProfileAdmin().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_profileMouseClicked

    private void namaProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaProfileMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() == 1){
            new profile_admin().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_namaProfileMouseClicked

    private void helloAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_helloAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_helloAncestorAdded

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       db.connect();
       try{
        conn = DriverManager.getConnection(url,user,pass);
           stmt = conn.createStatement();
          String login = ("SELECT * FROM logIn_admin");
          rs = stmt.executeQuery(login);
          rs.next();
          hello.setText("Hello ! , "+rs.getString(1));
          namaProfile.setText(rs.getString(1));
       }catch(SQLException e){
           Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, e);
       }
    }//GEN-LAST:event_formWindowActivated

    private void memberListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberListMouseClicked
        // TODO add your handling code here:
        new member_admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_memberListMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        db.connect();
        try{
        conn = DriverManager.getConnection(url,user,pass);
          stmt = conn.createStatement();
          String login = ("DELETE FROM login_admin ");
          stmt.executeUpdate(login);
          
        }catch(SQLException e){
            Logger.getLogger(driver.class.getName()).log(Level.SEVERE, null, e);
        }
        db.disconnect();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void btnPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeminjamanMouseClicked
        // TODO add your handling code here:
        new peminjamanBuku().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPeminjamanMouseClicked

    private void btnDataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataBukuMouseClicked
        // TODO add your handling code here:
        new dataBuku().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDataBukuMouseClicked

    private void inputCariMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCariMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCariMemberActionPerformed

    private void btnCariMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariMemberActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getRowCount();
        for(int a=0; a<row; a++) {
            tbMember.removeRow(0);
        }
        try {
            Connection konek = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugasakhir","root","");
            ResultSet rs = konek.createStatement().executeQuery("SELECT * FROM member where nama='"+inputCariMember.getText()+"'");
            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)};
                tbMember.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnClearSearch.setEnabled(true);
    }//GEN-LAST:event_btnCariMemberActionPerformed

    private void btnCariTbPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariTbPeminjamActionPerformed
        // TODO add your handling code here:
        int row = jTable2.getRowCount();
        for(int a=0; a<row; a++) {
            tbPeminjam.removeRow(0);
        }
        try {
            Connection konek = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugasakhir","root","");
            ResultSet rs = konek.createStatement().executeQuery("SELECT * FROM peminjaman where namaPeminjam='"+inputCariPeminjam.getText()+"'");
            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)};
                tbPeminjam.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnClearSearch.setEnabled(true);
    }//GEN-LAST:event_btnCariTbPeminjamActionPerformed

    private void btnCariTbBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariTbBukuActionPerformed
        // TODO add your handling code here:
        int row = jTable3.getRowCount();
        for(int a=0; a<row; a++) {
            tbBuku.removeRow(0);
        }
        try {
            Connection konek = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugasakhir","root","");
            ResultSet rs = konek.createStatement().executeQuery("SELECT * FROM buku where judul_buku='"+inputCariBuku.getText()+"'");
            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)};
                tbBuku.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnClearSearch.setEnabled(true);
    }//GEN-LAST:event_btnCariTbBukuActionPerformed

    private void btnClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSearchActionPerformed
        // TODO add your handling code here:
        new Dashboard_admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnClearSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariMember;
    private javax.swing.JButton btnCariTbBuku;
    private javax.swing.JButton btnCariTbPeminjam;
    private javax.swing.JButton btnClearSearch;
    private javax.swing.JLabel btnDataBuku;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel btnPeminjaman;
    private javax.swing.JLabel hello;
    private javax.swing.JTextField inputCariBuku;
    private javax.swing.JTextField inputCariMember;
    private javax.swing.JTextField inputCariPeminjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel labelTbMember;
    private javax.swing.JLabel memberList;
    private javax.swing.JLabel namaProfile;
    private javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables
}
