/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danda
 */
public class dataBuku extends javax.swing.JFrame {
    DefaultTableModel modell;
    /**
     * Creates new form dataBuku
     */
    public dataBuku() {
        initComponents();
        setTitle("Perpus.id");
        String []buku = {"ID Buku", "Judul Buku", "Penerbit", "Stok"};
        modell = new DefaultTableModel(buku, 0);
        jTable1.setModel(modell);
        tampilBuku();
        
        btnBackBuku.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelIdBuku = new javax.swing.JLabel();
        labelJudulBuku = new javax.swing.JLabel();
        labelPenerbit = new javax.swing.JLabel();
        labelStok = new javax.swing.JLabel();
        btnSubmitBuku = new javax.swing.JButton();
        inputIdBuku = new javax.swing.JTextField();
        inputJudulBuku = new javax.swing.JTextField();
        inputPenerbit = new javax.swing.JTextField();
        inputStok = new javax.swing.JTextField();
        btnBackBuku = new javax.swing.JButton();
        btnCariBuku = new javax.swing.JButton();
        inputCariBuku = new javax.swing.JTextField();
        labelDataBuku = new javax.swing.JLabel();
        labelCariBuku = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelBack.setBackground(new java.awt.Color(0, 0, 0));
        labelBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelBack.setForeground(new java.awt.Color(255, 255, 255));
        labelBack.setText("Kembali");
        labelBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelBackActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        labelIdBuku.setText("Id Buku");

        labelJudulBuku.setText("Judul Buku");

        labelPenerbit.setText("Penerbit");

        labelStok.setText("Stok");

        btnSubmitBuku.setBackground(new java.awt.Color(253, 137, 0));
        btnSubmitBuku.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSubmitBuku.setText("Submit");
        btnSubmitBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitBukuActionPerformed(evt);
            }
        });

        btnBackBuku.setBackground(new java.awt.Color(0, 0, 0));
        btnBackBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBackBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnBackBuku.setText("Back");
        btnBackBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackBukuActionPerformed(evt);
            }
        });

        btnCariBuku.setBackground(new java.awt.Color(0, 0, 0));
        btnCariBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnCariBuku.setText("Cari");
        btnCariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBukuActionPerformed(evt);
            }
        });

        labelDataBuku.setText("Data Buku");

        labelCariBuku.setText("Cari berdasarkan nama buku");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelIdBuku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(inputIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelJudulBuku)
                                .addGap(34, 34, 34)
                                .addComponent(inputJudulBuku))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPenerbit)
                                .addGap(45, 45, 45)
                                .addComponent(inputPenerbit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelStok)
                                .addGap(64, 64, 64)
                                .addComponent(inputStok))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelBack)
                                    .addComponent(btnSubmitBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 632, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDataBuku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBackBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelCariBuku)
                                .addGap(47, 47, 47)
                                .addComponent(inputCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelBack)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdBuku)
                    .addComponent(inputIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJudulBuku)
                    .addComponent(inputJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPenerbit)
                    .addComponent(inputPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStok)
                    .addComponent(inputStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnSubmitBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBackBuku)
                            .addComponent(labelDataBuku))
                        .addComponent(labelCariBuku, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCariBuku)
                        .addComponent(inputCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitBukuActionPerformed
        try {
            Connection konek = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugasakhir","root","");
            konek.createStatement().executeUpdate("insert into buku values"+"('"+inputIdBuku.getText()+"','"+inputJudulBuku.getText()+"','"+inputPenerbit.getText()+"','"+inputStok.getText()+"')");
            JOptionPane.showMessageDialog(null, "Berhasil menambahkan buku");
            tampilBuku();
        } catch (SQLException ex) {
            Logger.getLogger(dataBuku.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Gagal Menambahkan Buku","Error",0);
        }
    }//GEN-LAST:event_btnSubmitBukuActionPerformed
 
    private void labelBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelBackActionPerformed
        new Dashboard_admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_labelBackActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        if(i>-1) {
            inputIdBuku.setText(modell.getValueAt(i, 0).toString());
            inputIdBuku.setEnabled(false);
            
            inputJudulBuku.setText(modell.getValueAt(i, 1).toString());
            
            inputPenerbit.setText(modell.getValueAt(i, 2).toString());
            inputStok.setText(modell.getValueAt(i, 3).toString());
            
            btnSubmitBuku.setEnabled(false);
            btnBackBuku.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnBackBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackBukuActionPerformed
        new dataBuku().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackBukuActionPerformed

    private void btnCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBukuActionPerformed
        int row = jTable1.getRowCount();
        for(int a=0; a<row; a++) {
            modell.removeRow(0);
        }
        try {
            Connection konek = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugasakhir","root","");
            ResultSet rs = konek.createStatement().executeQuery("SELECT * FROM buku where judul_buku='"+inputCariBuku.getText()+"'");
            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)};
                modell.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(peminjamanBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCariBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackBuku;
    private javax.swing.JButton btnCariBuku;
    private javax.swing.JButton btnSubmitBuku;
    private javax.swing.JTextField inputCariBuku;
    private javax.swing.JTextField inputIdBuku;
    private javax.swing.JTextField inputJudulBuku;
    private javax.swing.JTextField inputPenerbit;
    private javax.swing.JTextField inputStok;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton labelBack;
    private javax.swing.JLabel labelCariBuku;
    private javax.swing.JLabel labelDataBuku;
    private javax.swing.JLabel labelIdBuku;
    private javax.swing.JLabel labelJudulBuku;
    private javax.swing.JLabel labelPenerbit;
    private javax.swing.JLabel labelStok;
    // End of variables declaration//GEN-END:variables

    private void tampilBuku(){
        int row = jTable1.getRowCount();
        for(int a=0; a<row; a++) {
            modell.removeRow(0);
        }
        try {
            Connection konek = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugasakhir","root","");
            ResultSet rs = konek.createStatement().executeQuery("SELECT * FROM buku");
            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)};
                modell.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(peminjamanBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
