/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhir;

import java.sql.*;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.logging.*;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class daftarAkun extends javax.swing.JFrame {
    Database db;
    Connection conn;
    ResultSet rs;
    public String url = "jdbc:mysql://localhost/tugasakhir";
    public String user = "root";
    public String pass = "";
    ArrayList<member> Member = new ArrayList();
    DefaultListModel<String> listMember = new DefaultListModel<>();
   
    
    /**
     * Creates new form daftarAkun
     */
    public daftarAkun() {
        initComponents();
        setTitle("Perpus.id");
        db = new Database();
        tampilData();
        
    }
    public void setNULL(){
        libIDTextField.setText("");
        namaTextField.setText("");
        noHpTextField.setText("");
        emailTextField.setText("");
        tgl.setSelectedItem("--");
        bulan.setSelectedItem("--");
        thn.setSelectedItem("--");
        passTextField.setText("");
    }
    public void inputValidation(){
        String tanggal="";
        tanggal+=tgl.getSelectedItem()+" ";
        tanggal+=bulan.getSelectedItem()+" ";
        tanggal+=thn.getSelectedItem()+" ";
        
        if (namaTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon Isi Nama");
            namaTextField.requestFocus();
        }else if(emailTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon isi Email");
            emailTextField.requestFocus();
        }else if(libIDTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon Isi Library Card ID");
            libIDTextField.requestFocus();
        }else if(passTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon Isi Password");
            passTextField.requestFocus();
        }else if(noHpTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon Isi No Handphone");
            noHpTextField.requestFocus();
        }else if(tanggal.equals("")){
            JOptionPane.showMessageDialog(null, "Mohon Isi No Handphone");
            tgl.requestFocus();
            bulan.requestFocus();
            thn.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null, "Berhasil Membuat Akun");
        }
    }
    public void tampilData(){
        try{
            String sql = "SELECT * FROM member";
            rs = db.getData(sql);
            while(rs.next()){
                String libID = rs.getString(1);
                String nama = rs.getString(2);
                String noHp = rs.getString(3);
                String email = rs.getString(4);
                Date tglLahir = rs.getDate(5);
                String Password = rs.getString(6);
                Member.add(new member(libID,nama,noHp,email,tglLahir,Password));
                listMember.addElement(libID);
            }
        } catch (SQLException ex) {
            Logger.getLogger(daftarAkun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        libIdLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        noHpLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        tglLahirLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        signUp = new javax.swing.JLabel();
        libIDTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        noHpTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        passTextField = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        tgl = new javax.swing.JComboBox<>();
        bulan = new javax.swing.JComboBox<>();
        thn = new javax.swing.JComboBox<>();
        admin = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(253, 137, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 567));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 567));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        libIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        libIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libIdLabel.setText("Library Id");
        libIdLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(libIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, 30));

        namaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namaLabel.setText("Nama");
        jPanel1.add(namaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, 30));

        noHpLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        noHpLabel.setText("No.Handphone");
        jPanel1.add(noHpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, 30));

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLabel.setText("Email");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, 30));

        tglLahirLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tglLahirLabel.setText("Tanggal Lahir");
        jPanel1.add(tglLahirLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        passLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passLabel.setText("Password");
        jPanel1.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, 30));

        signUp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        signUp.setText("Sign Up");
        jPanel1.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 100, -1));

        libIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libIDTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(libIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 260, 30));

        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(namaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 260, 30));

        noHpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noHpTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(noHpTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 260, 30));

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 260, 30));
        jPanel1.add(passTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 260, 30));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 110, -1));

        tgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));
        jPanel1.add(bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        thn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));
        jPanel1.add(thn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, -1, -1));

        admin.setBackground(new java.awt.Color(0, 0, 0));
        admin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/iconProfile.png"))); // NOI18N
        admin.setText("LOGIN");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        jPanel1.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 120, 110));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/bg perpusid.jpeg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libIDTextFieldActionPerformed

    private void noHpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noHpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noHpTextFieldActionPerformed

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        int bln = bulan.getSelectedIndex();
        String tanggal="";
        tanggal+=thn.getSelectedItem()+"-";
        tanggal+="0"+bln+"-";
        tanggal+=tgl.getSelectedItem();
        
        try{
           
            conn = DriverManager.getConnection(url,user,pass);
            conn.createStatement().executeUpdate("INSERT INTO member VALUES ('"+ libIDTextField.getText()+"','"
                                                + namaTextField.getText()+"','"+ noHpTextField.getText()+"','"
                                                + emailTextField.getText()+"','"+ tanggal+"','"
                                                +passTextField.getText()+"')");
            inputValidation();
            setNULL();
            
        } catch (SQLException ex) {
            Logger.getLogger(daftarAkun.class.getName()).log(Level.SEVERE, null, ex);
            String libID = libIDTextField.getText();
            if(db.ValidateDuplicate(libID)){
            JOptionPane.showMessageDialog(null, "Library ID sudah Ada!", "Error", 0);
            }
            JOptionPane.showMessageDialog(null, "Gagal Membuat Akun");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        for(int i=1;i<=31;i++){
            tgl.addItem(""+i);
        }
        
        bulan.addItem("Januari");
        bulan.addItem("Februari");
        bulan.addItem("Maret");
        bulan.addItem("April");
        bulan.addItem("Mei");
        bulan.addItem("Juni");
        bulan.addItem("Juli");
        bulan.addItem("Agustus");
        bulan.addItem("September");
        bulan.addItem("Oktober");
        bulan.addItem("November");
        bulan.addItem("Desember");
        
        for(int i=1921;i<=2021;i++){
            thn.addItem(""+i);
        }
    }//GEN-LAST:event_formWindowActivated

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            new Login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_adminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftarAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftarAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftarAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftarAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftarAkun().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> bulan;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField libIDTextField;
    private javax.swing.JLabel libIdLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel noHpLabel;
    private javax.swing.JTextField noHpTextField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passTextField;
    private javax.swing.JLabel signUp;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox<String> tgl;
    private javax.swing.JLabel tglLahirLabel;
    private javax.swing.JComboBox<String> thn;
    // End of variables declaration//GEN-END:variables
    
}
