/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhir;
import mulaiRunDriverDisini.driver;
import java.sql.*;
import java.sql.DriverManager;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.*;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author ASUS
 */
public class Dashboard extends javax.swing.JFrame {
Database db;
    Connection conn;
    ResultSet rs;
    Statement stmt = null;
    public String url = "jdbc:mysql://localhost/tugasakhir";
    public String user = "root";
    public String pass = "";
    ArrayList<member> Member = new ArrayList();
    DefaultListModel<String> listMember = new DefaultListModel<>();
    LocalDate tanggal; 
    DefaultListModel<String> listBuku = new DefaultListModel<>();
   
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        db = new Database();
        tampilData();
       tampilBuku();
    }
    public void tampilData(){
        try{
            String sql = "SELECT * FROM member";
            rs = db.getData(sql);
            while(rs.next()){
                String libID = rs.getString(1);
                String nama = rs.getString(2);
                String noHp = rs.getString(3);
                String email = rs.getString(4);
                Date tglLahir = rs.getDate(5);
                String Password = rs.getString(6);
                Member.add(new member(libID,nama,noHp,email,tglLahir,Password));
                listMember.addElement(libID);
            }
        } catch (SQLException ex) {
            Logger.getLogger(daftarAkun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void tampilBuku(){
            try{
                String query = "SELECT * FROM buku";
                rs = db.getData(query);
            while(rs.next()){
                
                int a = rs.getInt(1);
                String b = rs.getString(2);
                String c = rs.getString(3);
                int d = rs.getInt(4);
                
                listBuku.addElement(b);
            }
            
            jList2.setModel(listBuku);
        } catch (SQLException ex) {
            Logger.getLogger(daftarAkun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pinjamBuku = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        iconBuku = new javax.swing.JLabel();
        idBuku = new javax.swing.JLabel();
        jdlBuku = new javax.swing.JLabel();
        penerbit = new javax.swing.JLabel();
        stok = new javax.swing.JLabel();
        Pinjam = new javax.swing.JToggleButton();
        meminjamBku = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        btnBack2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tglPinjam1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        stok1 = new javax.swing.JLabel();
        jdlBuku1 = new javax.swing.JLabel();
        penerbit1 = new javax.swing.JLabel();
        id_buku = new javax.swing.JLabel();
        pnjmBuku = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        background1 = new javax.swing.JLabel();
        meminjamBuku = new javax.swing.JLabel();
        mengembalikanBuku = new javax.swing.JLabel();
        hello = new javax.swing.JLabel();
        namaProfile = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        rcmndd = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        bukuDilan = new javax.swing.JLabel();
        bukuAyam = new javax.swing.JLabel();
        bukuHabibi = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        pinjamBuku.setSize(new java.awt.Dimension(860, 740));
        pinjamBuku.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setMinimumSize(new java.awt.Dimension(860, 710));
        jPanel2.setPreferredSize(new java.awt.Dimension(860, 710));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(iconBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 210, 260));

        idBuku.setText("jLabel2");
        jPanel2.add(idBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jdlBuku.setText("jLabel2");
        jPanel2.add(jdlBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, 20));

        penerbit.setText("jLabel2");
        jPanel2.add(penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        stok.setText("jLabel2");
        jPanel2.add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        Pinjam.setText("Pinjam");
        Pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinjamActionPerformed(evt);
            }
        });
        jPanel2.add(Pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 110, 40));

        pinjamBuku.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 710));

        meminjamBku.setSize(new java.awt.Dimension(900, 567));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/backBtn.png"))); // NOI18N
        btnBack2.setText("Back");
        btnBack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBack2MouseClicked(evt);
            }
        });
        jPanel3.add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 50, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Perpus.id");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 120, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Meminjam Buku");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 410, 70));

        tglPinjam1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tglPinjam1.setForeground(new java.awt.Color(255, 255, 255));
        tglPinjam1.setText("List Buku Yang Tersedia");
        jPanel3.add(tglPinjam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 92, -1, 30));

        jPanel4.setBackground(new java.awt.Color(253, 153, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("Detail Buku");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        stok1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stok1.setText("Stok");
        jPanel4.add(stok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jdlBuku1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jdlBuku1.setText("Judul Buku");
        jPanel4.add(jdlBuku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        penerbit1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        penerbit1.setText("Penerbit");
        jPanel4.add(penerbit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        id_buku.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id_buku.setText("Id Buku");
        jPanel4.add(id_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        pnjmBuku.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pnjmBuku.setText("Pinjam Buku");
        pnjmBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnjmBukuActionPerformed(evt);
            }
        });
        jPanel4.add(pnjmBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 305, 340, 50));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 480, 370));

        jList2.setBackground(new java.awt.Color(153, 153, 153));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "--" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 190, 370));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/bgHistory.png"))); // NOI18N
        jPanel3.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout meminjamBkuLayout = new javax.swing.GroupLayout(meminjamBku.getContentPane());
        meminjamBku.getContentPane().setLayout(meminjamBkuLayout);
        meminjamBkuLayout.setHorizontalGroup(
            meminjamBkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        meminjamBkuLayout.setVerticalGroup(
            meminjamBkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        meminjamBuku.setBackground(new java.awt.Color(255, 255, 255));
        meminjamBuku.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        meminjamBuku.setForeground(new java.awt.Color(255, 255, 255));
        meminjamBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/iconBuku.png"))); // NOI18N
        meminjamBuku.setText("Meminjam Buku ");
        meminjamBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meminjamBukuMouseClicked(evt);
            }
        });
        getContentPane().add(meminjamBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 190, 50));

        mengembalikanBuku.setBackground(new java.awt.Color(255, 255, 255));
        mengembalikanBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mengembalikanBuku.setForeground(new java.awt.Color(255, 255, 255));
        mengembalikanBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/iconKertas.png"))); // NOI18N
        mengembalikanBuku.setText("History Meminjam");
        mengembalikanBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mengembalikanBukuMouseClicked(evt);
            }
        });
        getContentPane().add(mengembalikanBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 190, 50));

        hello.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hello.setForeground(new java.awt.Color(255, 255, 255));
        hello.setText("--");
        hello.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                helloAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(hello, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 320, 60));

        namaProfile.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        namaProfile.setForeground(new java.awt.Color(255, 255, 255));
        namaProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaProfile.setText("--");
        namaProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaProfileMouseClicked(evt);
            }
        });
        getContentPane().add(namaProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/iconProfile.png"))); // NOI18N
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, 70));

        rcmndd.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        rcmndd.setText("Trending !");
        getContentPane().add(rcmndd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 120, -1));

        btnSearch.setBackground(new java.awt.Color(153, 0, 153));
        btnSearch.setForeground(new java.awt.Color(153, 0, 153));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/iconSearch.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 40, -1));
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 120, 30));

        jPanel1.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 2));
        jPanel1.setForeground(new java.awt.Color(153, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bukuDilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/bukuDilan 1 (1).png"))); // NOI18N
        bukuDilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuDilanMouseClicked(evt);
            }
        });
        jPanel1.add(bukuDilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        bukuAyam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/bukuAyamKampung 1.png"))); // NOI18N
        bukuAyam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuAyamMouseClicked(evt);
            }
        });
        jPanel1.add(bukuAyam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        bukuHabibi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/bukuHabibi.png"))); // NOI18N
        bukuHabibi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuHabibiMouseClicked(evt);
            }
        });
        jPanel1.add(bukuHabibi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 620, 410));

        background.setBackground(new java.awt.Color(204, 0, 204));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/4 Dashboard.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helloAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_helloAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_helloAncestorAdded

    private void meminjamBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meminjamBukuMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() == 1){
            meminjamBku.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_meminjamBukuMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

       db.connect();
       try{
        conn = DriverManager.getConnection(url,user,pass);
           stmt = conn.createStatement();
          String login = ("SELECT * FROM log_in");
          rs = stmt.executeQuery(login);
          rs.next();
          hello.setText("Hello,   "+rs.getString(2));
          namaProfile.setText(rs.getString(2));
       }catch(SQLException e){
           Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, e);
       }
    }//GEN-LAST:event_formWindowActivated

    private void mengembalikanBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mengembalikanBukuMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            new historyPinjam().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_mengembalikanBukuMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        db.connect();
        try{
        conn = DriverManager.getConnection(url,user,pass);
          stmt = conn.createStatement();
          String login = ("DELETE FROM log_in ");
          stmt.executeUpdate(login);
          
        }catch(SQLException e){
            Logger.getLogger(driver.class.getName()).log(Level.SEVERE, null, e);
        }
        db.disconnect();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() == 1){
            new profile().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_profileMouseClicked

    private void namaProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaProfileMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            new profile().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_namaProfileMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
        db.connect();
        try{
        conn = DriverManager.getConnection(url,user,pass);
          stmt = conn.createStatement();
          String login = ("DELETE FROM log_in");
          stmt.executeUpdate(login);
          
        }catch(SQLException e){
            Logger.getLogger(driver.class.getName()).log(Level.SEVERE, null, e);
        }
        db.disconnect();
        JOptionPane.showMessageDialog(rootPane,"Anda telah Logout","Success",1);
        System.exit(0);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void bukuDilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuDilanMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() == 1){
            try{
            conn = DriverManager.getConnection(url,user,pass);
           stmt = conn.createStatement();
          String login = ("SELECT * FROM buku WHERE id_buku='"+"13"+"'");
          rs = stmt.executeQuery(login);
          rs.next();
          

            pinjamBuku.setVisible(true);
            idBuku.setText("ID Buku: "+rs.getString(1));
            iconBuku.setIcon(bukuDilan.getIcon());
            jdlBuku.setText("Judul Buku :       "+rs.getString(2));
            penerbit.setText("Penerbit :       "+rs.getString(3));
            stok.setText("Stok Buku  :    "+rs.getString(4));
         
            }catch(SQLException e){
                Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_bukuDilanMouseClicked

    private void bukuAyamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuAyamMouseClicked
        // TODO add your handling code here:    
        if(evt.getClickCount() == 1){
            try{
            conn = DriverManager.getConnection(url,user,pass);
           stmt = conn.createStatement();
          String login = ("SELECT * FROM buku WHERE judul_buku='"+"22"+"'");
          rs = stmt.executeQuery(login);
          rs.next();
          

            pinjamBuku.setVisible(true);
            idBuku.setText("Id Buku: "+rs.getString(1));
            iconBuku.setIcon(bukuAyam.getIcon());
            jdlBuku.setText("Judul Buku :      "+rs.getString(2));
            penerbit.setText("Penerbit  :      "+rs.getString(3));
            stok.setText("Stok Buku   :   "+rs.getString(4));
            }catch(SQLException e){
                Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_bukuAyamMouseClicked

    private void bukuHabibiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuHabibiMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            try{
                conn = DriverManager.getConnection(url,user,pass);
                stmt = conn.createStatement();
                String login = ("SELECT * FROM buku WHERE judul_buku='"+"69"+"'");
                rs = stmt.executeQuery(login);
                rs.next();
                
                pinjamBuku.setVisible(true);
                idBuku.setText("Id Buku: "+rs.getString(1));
                iconBuku.setIcon(bukuHabibi.getIcon());
                jdlBuku.setText("Judul Buku :      "+rs.getString(2));
                penerbit.setText("Penerbit  :      "+rs.getString(3));
                stok.setText("Stok Buku   :   "+rs.getString(4));
            }catch(SQLException e){
                Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_bukuHabibiMouseClicked

    private void PinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinjamActionPerformed
        // TODO add your handling code here:
        db.connect();
        Statement stm;
        ResultSet buku;
        Connection konek;
        String id = idBuku.getText();
        String a = id.substring(9,11);
        
         try{
          conn = DriverManager.getConnection(url,user,pass);
          stmt = conn.createStatement();
          String peminjam = ("SELECT * FROM log_in");
          rs = stmt.executeQuery(peminjam);
          rs.next();
          
          konek = DriverManager.getConnection(url,user,pass);
          stm = konek.createStatement();
          String p = "SELECT * FROM buku WHERE id_buku ='"+a+"'";
          buku = stm.executeQuery(p);
          buku.next();
          stmt.executeUpdate("INSERT INTO peminjaman VALUES('"+rs.getString(1)+"','"+rs.getString(2)+"','"+buku.getString(1)+"','"+buku.getString(2)+"','"+tanggal.now()+"')");
          JOptionPane.showMessageDialog(null,"Berhasil Meminjam","Success",1);
          
        } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Gagal Meminjam", "Error", 0);
            }
    }//GEN-LAST:event_PinjamActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String buku = search.getText();
        Icon icoooon = getIcon(buku);
            try{
                conn = DriverManager.getConnection(url,user,pass);
                stmt = conn.createStatement();
                String login = ("SELECT * FROM buku WHERE judul_buku='"+buku+"'");
                rs = stmt.executeQuery(login);
                rs.next();
                
                pinjamBuku.setVisible(true);
                idBuku.setText("Id Buku: "+rs.getString(1));
                iconBuku.setIcon(icoooon);
                jdlBuku.setText("Judul Buku :      "+rs.getString(2));
                penerbit.setText("Penerbit  :      "+rs.getString(3));
                stok.setText("Stok Buku   :   "+rs.getString(4));
            
   
            }catch(SQLException e){
                Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, e);
                pinjamBuku.setVisible(false);
                JOptionPane.showMessageDialog(null, "Buku tidak ditemukan","Error",0);
            }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBack2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack2MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            new Dashboard().setVisible(true);
            meminjamBku.setVisible(false);
        }
    }//GEN-LAST:event_btnBack2MouseClicked

    private void pnjmBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnjmBukuActionPerformed
        // TODO add your handling code here:
        search.setText(jList2.getSelectedValue());
        String buku = search.getText();
        
        try{
            conn = DriverManager.getConnection(url,user,pass);
            stmt = conn.createStatement();
            String login = ("SELECT * FROM buku WHERE judul_buku='"+jList2.getSelectedValue()+"'");
            rs = stmt.executeQuery(login);
            rs.next();
                
            pinjamBuku.setVisible(true);
            idBuku.setText("Id Buku: "+rs.getString(1));
            jdlBuku.setText("Judul Buku :      "+rs.getString(2));
            penerbit.setText("Penerbit  :      "+rs.getString(3));
            stok.setText("Stok Buku   :   "+rs.getString(4));
            
            iconBuku.setIcon(getIcon(buku));
        }catch(SQLException e){
           Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_pnjmBukuActionPerformed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            try{
                String query = "SELECT * FROM buku where judul_buku ='"+jList2.getSelectedValue()+"'";
                conn = DriverManager.getConnection(url,user,pass);
                stmt = conn.createStatement();

                rs = stmt.executeQuery(query);
                rs.next();
                id_buku.setText("Id Buku : "+rs.getString(1));
                jdlBuku1.setText("Judul Buku : "+rs.getString(2));
                penerbit1.setText("Penerbit: "+rs.getString(3));
                stok1.setText("Stok : " + rs.getString(4));
                
            } catch (SQLException e ){
                Logger.getLogger(Database.class.getName()).log(Level.SEVERE,null,e);
            }
        }
    }//GEN-LAST:event_jList2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Pinjam;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel btnBack2;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel bukuAyam;
    private javax.swing.JLabel bukuDilan;
    private javax.swing.JLabel bukuHabibi;
    private javax.swing.JLabel hello;
    private javax.swing.JLabel iconBuku;
    private javax.swing.JLabel idBuku;
    private javax.swing.JLabel id_buku;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jdlBuku;
    private javax.swing.JLabel jdlBuku1;
    private javax.swing.JDialog meminjamBku;
    private javax.swing.JLabel meminjamBuku;
    private javax.swing.JLabel mengembalikanBuku;
    private javax.swing.JLabel namaProfile;
    private javax.swing.JLabel penerbit;
    private javax.swing.JLabel penerbit1;
    private javax.swing.JDialog pinjamBuku;
    private javax.swing.JButton pnjmBuku;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel rcmndd;
    private javax.swing.JTextField search;
    private javax.swing.JLabel stok;
    private javax.swing.JLabel stok1;
    private javax.swing.JLabel tglPinjam1;
    // End of variables declaration//GEN-END:variables
    public Icon getIcon(String jdul){
        jdul = search.getText();
        Icon icon1 = null;
        if(jdul.equals("Dilan")){
            icon1=(bukuDilan.getIcon());
        }else if(jdul.equals("Ayam Kampung")){
            icon1=(bukuAyam.getIcon());
        }else if(jdul.equals("Rudy Habibie")){
            icon1=(bukuHabibi.getIcon());
        }
        return icon1;
    }

}

