/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhir;

import admin.Dashboard_admin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;

/**
 *
 * @author ASUS
 */
public class profile extends javax.swing.JFrame {
   Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    public String url = "jdbc:mysql://localhost/tugasakhir";
    public String user = "root";
    public String pass = "";
    Database db;
    ArrayList<member> Member = new ArrayList();
    DefaultListModel<String> listMember = new DefaultListModel<>();
    /**
     * Creates new form profile
     */
    public profile() {
        initComponents();
        db = new Database();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileAdmin = new javax.swing.JDialog();
        admLibId = new javax.swing.JLabel();
        passAdm = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        profLibId = new javax.swing.JLabel();
        profNama = new javax.swing.JLabel();
        profNoHP = new javax.swing.JLabel();
        profEmail = new javax.swing.JLabel();
        profTgl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        profileAdmin.setSize(new java.awt.Dimension(630, 567));
        profileAdmin.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                profileAdminWindowActivated(evt);
            }
        });
        profileAdmin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admLibId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        admLibId.setText("LibraryId");
        admLibId.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        profileAdmin.getContentPane().add(admLibId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 190, 170));

        passAdm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passAdm.setText("Password");
        passAdm.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        profileAdmin.getContentPane().add(passAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 260, 200));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Profile");
        profileAdmin.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Perpus.id");
        profileAdmin.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 110, 50));

        btnBack1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/backBtn.png"))); // NOI18N
        btnBack1.setText("Back");
        btnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBack1MouseClicked(evt);
            }
        });
        profileAdmin.getContentPane().add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 60));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/profileBG.png"))); // NOI18N
        profileAdmin.getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(627, 569));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profLibId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        profLibId.setText("LibraryId");
        getContentPane().add(profLibId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 300, -1));

        profNama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        profNama.setText("Nama ");
        getContentPane().add(profNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 440, -1));

        profNoHP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        profNoHP.setText("No.Hanphone");
        getContentPane().add(profNoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 450, -1));

        profEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        profEmail.setText("Email");
        getContentPane().add(profEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 450, -1));

        profTgl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        profTgl.setText("Tanggal Lahir");
        getContentPane().add(profTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 450, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Profile");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Perpus.id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 110, 50));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/backBtn.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/profileBG.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            new Dashboard().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnBackMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
                // TODO add your handling code here:

       db.connect();
       try{
        conn = DriverManager.getConnection(url,user,pass);
           stmt = conn.createStatement();
          String login = ("SELECT * FROM log_in");
          rs = stmt.executeQuery(login);
          rs.next();
          profLibId.setText("Library Id : "+rs.getString(1));
          profNama.setText ("Nama           "+rs.getString(2));
          profNoHP.setText ("No.Handphone   "+rs.getString(3));
          profEmail.setText("Email          "+rs.getString(4));
          profTgl.setText  ("Tanggal Lahir  "+rs.getString(5));

       }catch(SQLException e){
           Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, e);
       }
    }//GEN-LAST:event_formWindowActivated

    private void btnBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            new Dashboard_admin().setVisible(true);
        }
    }//GEN-LAST:event_btnBack1MouseClicked

    private void profileAdminWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_profileAdminWindowActivated
        // TODO add your handling code here:
        
       db.connect();
       try{
        conn = DriverManager.getConnection(url,user,pass);
           stmt = conn.createStatement();
          String login = ("SELECT * FROM logIn_admin");
          rs = stmt.executeQuery(login);
          rs.next();
          admLibId.setText("Library Id "+":"+rs.getString(1));
          passAdm.setText("Password "+":"+rs.getString(2));

       }catch(SQLException e){
           Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, e);
       }
    }//GEN-LAST:event_profileAdminWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admLibId;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnBack1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel passAdm;
    private javax.swing.JLabel profEmail;
    private javax.swing.JLabel profLibId;
    private javax.swing.JLabel profNama;
    private javax.swing.JLabel profNoHP;
    private javax.swing.JLabel profTgl;
    private javax.swing.JDialog profileAdmin;
    // End of variables declaration//GEN-END:variables
    public JDialog getProfileAdmin(){
        return profileAdmin;
    }
}
